export const RESISTER_START = "RESISTER_START";
export const RESISTER_SUCCESS = "RESISTER_SUCCESS";
export const RESISTER_FAIL = "RESISTER_FAIL";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const SET_USER = "SET_USER";

export const GOOGLE_SIGNIN_START = "GOOGLE_SIGNIN_START";
export const GOOGLE_SIGNIN_SUCCESS = "GOOGLE_SIGNIN_SUCCESS";
export const GOOGLE_SIGNIN_FAIL = "GOOGLE_SIGNIN_FAIL";

export const GOOGLE_VERIFICATION_START = "GOOGLE_VERIFICATION_START";
export const GOOGLE_VERIFICATION_SUCCESS = "GOOGLE_VERIFICATION_SUCCESS";
export const GOOGLE_VERIFICATION_FAIL = "GOOGLE_VERIFICATION_FAIL";

export const FACEBOOK_SIGNIN_START = "FACEBOOK_SIGNIN_START";
export const FACEBOOK_SIGNIN_SUCCESS = "FACEBOOK_SIGNIN_SUCCESS";
export const FACEBOOK_SIGNIN_FAIL = "FACEBOOK_SIGNIN_FAIL";